FROM node:17-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /tanjalo_web
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn install
# Copy app files
COPY . .
# Expose port
EXPOSE 3002
# Start the app
CMD [ "yarn", "start" ]